### ISSUE TITLE
Warmup-Error

### ISSUE THREAD

**Issue by srhinow** [netzmacht/workflow#2]
Wenn ich das Paket per composer installiere bekomme ich zum schluss beim warmup nen Error:
```
Attempted to load class "MetaPalettes" from the global namespace.                       
    Did you forget a "use" statement for "ContaoCommunityAlliance\MetaPalettes\             
    MetaPalettes"? 
```
das in den drei dca-Dateien tl_user_group.php, tl_user.php und tl_member_group.php. Wenn man dort "\MetaPalettes" mit dem Namespace "\ContaoCommunityAlliance\MetaPalettes\MetaPalettes" ergänzt, dann läuft der Warmup auch ohne Fehler durch.

**Comment by dmolineus** [comment]
This issue isn't relateted to netzmacht/workflow but to netzmacht/contao-workflow where you already created an issue for it: https://github.com/netzmacht/contao-workflow/issues/6
